# 넘파이 ndarray 개요

##### ndarray란? => numpy 기반 데이터 타입! 다차원(Multi-dimen-sion)배열을 생성 및 다양한 연산을 수행 가능

In [16]:
import numpy as np

In [17]:
array1 = np.array([1,2,3]) # array(): 다양한 인자를 입력받아 ndarray로 변환 
print('arra1 type:', type(array1)) # 해당 변수의 데이터 타입을 반환 ex. ndarray, list...
print('array1 array 형태:', array1.shape) # shape: ndarray의 차원과 크기를 튜플(tuple) 형태로 반환


arra1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


In [18]:
print(array1)

[1 2 3]


In [7]:
array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)
# 2개의 row와 3개의 col을 가지고 있는 2차원 array

array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)


In [9]:
array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)
# 1개의 row와 3개의 col을 가지고 있는 '2차원 데이터'
# array1과는 구분되는 2차원 데이터!

array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [10]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:3}차원'.format(array1.ndim, array2.ndim, array3.ndim))
# ndim: ndarray의 차원을 반환

array1: 1차원, array2: 2차원, array3:   2차원


# ndaaray의 데이터 타입

In [12]:
list1 = [1,2,3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype) # dtype: ndarray 내의 데이터 타입을 반환

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


##### ndarray 내의 데이터 타입은 모두 같아야 함

In [42]:
# ndarray 내의 데이터 타입이 하나라도 다를 경우, 데이터 크기가 '더 큰' 데이터 타입으로 형 변환을 일괄 적용

list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)
# int형과 string형이 섞여 있을 경우, int형을 string형으로 변환

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)
# int형과 float형이 섞여 있을 경우, int형을 float형으로 변환

list4 = [2.7, 'test']
array4 = np.array(list4)
print(array4, array4.dtype)
# float형과 string형이 섞여 있을 경우, float형을 string형으로 변환 

['1' '2' 'test'] <U11
[1. 2. 3.] float64
['2.7' 'test'] <U32


In [19]:
# int형을 float형으로 변경
array_int = np.array([1,2,3])
array_float = array_int.astype('float64') # astype(): ndarray 내 데이터 값의 타입을 변경
print(array_float, array_float.dtype)

# 위 작업을 통해 생성된 float형 ndaray를 int형으로 변경
array_int2 = array_float.astype('int32')
print(array_int2, array_int2.dtype)

# float형을 int형으로 변경 (소수점 이하는 모두 없어짐)
array_float2 = np.array([1.1, 2.1, 3.1])
array_int3 = array_float.astype('int32')
print(array_int3, array_int3.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


# ndarray를 편리하게 생성하기 - arange, zeros, ones

###### arange(): 0부터 'stop값 - 1'까지의 수를 순차적으로 ndarray의 데이터 값으로 변환
###### start값을 설정하지 않을 시, 0으로 자동 지정 

In [19]:
for i in range(0, 10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [24]:
sequence_array = np.arange(10) 
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


##### zeros(): 튜플 형태의 shape값을 입력하면 모든 값을 0으로 채운 ndarray를 반환 

In [25]:
zero_array = np.zeros((3,2), dtype='int32') 
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [26]:
print(np.zeros_like(sequence_array))

[0 0 0 0 0 0 0 0 0 0]


##### ones(): 튜플 형태의 shape값을 입력하면 모든 값을 1로 채운 ndarray를 반환

In [45]:
one_array = np.ones((3,2)) # dtype을 지정하지 않을 경우 기본 반환형은 float형
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


# ndarray의 차원과 크기를 변경하는 reshape()

In [25]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5) # row:2, col:5 형태의 array로 변환
print('array2:\n', array2)

array3 = array1.reshape(5,2) # row: 5, col:2 형태의 array로 변환
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [27]:
# 지정된 사이즈로 변경이 불가능할 경우 ValueError 발생
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [28]:
# reshape()에서 인자로 -1을 사용할 경우, 원래의 ndarray와 호환되는 새로운 shape로 변환
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)

array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [29]:
# 이 경우에도 호환될 수 없는 형태는 변환 불가
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [29]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist()) # tolist(): list 자료형으로 변환

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,2)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0, 1], [2, 3], [4, 5], [6, 7]]
array5 shape: (4, 2)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [32]:
# 출력값을 list로 변환하지 않은 경우

array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d, '\n')

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n', array5)
print('array5 shape:', array5.shape, '\n')

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6)
print('array6 shape:', array6.shape)

array3d:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 

array5:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
array5 shape: (8, 1) 

array6:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
array6 shape: (8, 1)


# 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

### 단일 값 추출

In [34]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

# index는 0부터 시작. array1[2]는 3임
value = array1[2]
print('array1[2] value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
array1[2] value: 3
<class 'numpy.int32'>


In [36]:
# 맨뒤의 값은 array[-1], 뒤에서 두번째 값은 array[-2]로 추출 가능
print('맨 뒤의 값:', array1[-1], ' 맨 뒤에서 두 번째 값:', array1[-2]) # java [-1]

맨 뒤의 값: 9  맨 뒤에서 두 번째 값: 8


In [37]:
# index를 이용하여 배열 내 값을 수정할 수 있음
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


##### 2차원 ndarray에서의 단일 값 추출

In [38]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0, 0])
print('(row=0, col=1) index 가리키는 값:', array2d[0, 1])
print('(row=1, col=0) index 가리키는 값:', array2d[1, 0])
print('(row=2, col=2) index 가리키는 값:', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [39]:
# 넘파이 ndarray에서 row = axis0, col = axis1
print('(axis0=0, axis1=0) index 가리키는 값:', array2d[0, 0])
print('(axis0=0, axis1=1) index 가리키는 값:', array2d[0, 1])
print('(axis0=1, axis1=0) index 가리키는 값:', array2d[1, 0])
print('(axis0=2, axis1=2) index 가리키는 값:', array2d[2, 2])

(axis0=0, axis1=0) index 가리키는 값: 1
(axis0=0, axis1=1) index 가리키는 값: 2
(axis0=1, axis1=0) index 가리키는 값: 4
(axis0=2, axis1=2) index 가리키는 값: 9


### 슬라이싱

In [40]:
# indexing을 통한 '단일 데이터 값 추출'을 제외하고, 
# 슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 'ndarray' 타입!
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [41]:
array1 = np.arange(start=1, stop=10)
# 시작 인덱스를 생략할 경우 자동으로 맨 처음 인덱스인 0으로 간주
array4 = array1[:3]
print(array4)
# 종료 인덱스를 생략할 경우 자동으로 맨 마지막 인덱스로 간주
array5 = array1[3:]
print(array5)
# 시작/종료 인덱스를 생략할 경우 자동으로 맨 처음/맨 마지막 인덱스로 간주
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


##### 2차원 배열에서의 슬라이싱

In [30]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d, '\n')

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2], '\n')
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3], '\n')
print('array2d[1:3, :]\n', array2d[1:3, :], '\n')
print('array2d[:, :]\n', array2d[:, :], '\n')
print('array2d[:2, 0]\n', array2d[:2, 0], '\n') # 한쪽에는 슬라이싱을, 한쪽에는 단일 값을 적용해도 ok

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

array2d[0:2, 0:2]
 [[1 2]
 [4 5]] 

array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]] 

array2d[1:3, :]
 [[4 5 6]
 [7 8 9]] 

array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

array2d[:2, 0]
 [1 4] 



In [32]:
# 2차원 ndarray에서 뒤에 오는 인덱스를 없애면, 1차원 ndarray 반환
print(array2d[0])
print(array2d[:,1])
print('array2d[0] shape:', array2d[0].shape)
print('array2d[1] shape:', array2d[1].shape)

# 마찬가지로, 3차원 ndarray에서 뒤에 오는 인덱스를 없애면, 2차원 ndarray 반환

[1 2 3]
[2 5 8]
array2d[0] shape: (3,)
array2d[1] shape: (3,)


### 팬시 인덱싱 (Fancy Indexing)
###### 리스트나 ndarray로 인덱스 집합을 지정하면, 해당 위치의 index에 해당하는 ndarray를반환

In [34]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

# (row, col) 인덱스가 -> (0,2),(1,2)로 적용됨
array3 = array2d[[0,1], 2]
print('array2d[0,1, 2] =>', array3.tolist())

# ((0,0),(0,1)), ((1,0), (1,1))
array4 = array2d[[0,2], 0:2]
print('array2d[[0,2], 0:2] =>', array4.tolist())

# ((0,:), (1,:))
array5 = array2d[[0,1]]
print('array2d[0,1] =>', array5.tolist())

array2d[0,1, 2] => [3, 6]
array2d[0,1, 0:2] => [[1, 2], [7, 8]]
array2d[0,1] => [[1, 2, 3], [4, 5, 6]]


### 불린 인덱싱 (Boolean Indexing)
##### 조건문을 입력 받아, 조건 필터링과 검색을 동시에 가능하게 함

In [35]:
array1d = np.arange(start=1, stop=10)
print(array1d)

# []안에 'array1d > 5' 불린 인덱싱을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값:', array3)

[1 2 3 4 5 6 7 8 9]
array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


##### 조건문에 따라 ndarray 내 데이터 값을 True/False로 분류,
##### True 값이 있는 위치 인덱스 값을 자동으로 변환하여, 해당 인덱스 위치의 데이터만 반환

In [36]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [62]:
# 직접 boolean 인덱스 집합을 만들어 대입해도 같은 결과!
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링한 결과:', array3)

indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

불린 인덱스로 필터링한 결과: [6 7 8 9]
일반 인덱스로 필터링 결과: [6 7 8 9]


### 행렬의 정렬 - sort()와 argsort()
##### 행렬 정렬
##### np.sort(): 원 행렬은 그대로 유지한 채 행렬의 정렬된 행렬을 반환

In [64]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]


###### ndarray.sort(): 원 행렬 자체를 정렬한 형태로 변환, 반환 값은 None

In [65]:
sort_array2 = org_array.sort()
print('ndarray.sort() 호출 후 반환된 정렬 행렬:', sort_array2)
print('ndarray.sort() 호출 후 원본 행렬:', org_array)

ndarray.sort() 호출 후 반환된 정렬 행렬: None
ndarray.sort() 호출 후 원본 행렬: [1 3 5 9]


###### 내림차순 정렬: [::-1] 적용

In [67]:
sort_array1_desc = np.sort(org_array)[::-1]
print(sort_array1_desc)

[9 5 3 1]


##### 2차원 이상의 행렬 정렬: axis 축 값 설정을 통해 row / col 방향으로 정렬을 수행

In [5]:
array2d = np.array([[8, 12],
                    [7, 1]])

# row 방향(=위에서 아래로)으로 정렬 
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

# col 방향(=왼쪽에서 오른쪽으로 정렬)
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [7]:
print(np.sort(array2d, axis=1)[::-1])

[[ 1  7]
 [ 8 12]]


### 정렬된 행렬의 인덱스를 반환하기
##### np.argsort(): 정렬 행렬의 인덱스를 ndarray형으로 반환

In [71]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
# 정렬 결과: [1, 3, 5, 9]
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [72]:
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
# 정렬 결과: [9, 5, 3, 1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


##### np.argsort() 활용법

In [75]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
# 오름차순 정렬 결과: [78, 84, 88, 95, 98]
# 각각의 원래 인덱스: [0, 2, 4, 1, 3]

print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


# 선형대수 연산 - 행렬 내적과 전치 행렬 구하기
### 행렬 내적 (행렬 곱): 왼쪽 행렬의 row와 오른쪽 행렬의 col의 원소들을 순차적으로 곱한 뒤 그 결과를 모두 더한 값
##### 왼쪽 행렬의 열 개수와 오른쪽 행렬의 행 개수가 동일해야 내적 연산 가능
##### np.dot(): 행렬 내적 함수

In [76]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


### 전치 행렬: 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬
##### np.transpose(): 전치 행렬 함수

In [78]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
